// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_end_vozTrip.Services;

#nullable disable

namespace back_end_vozTrip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_end_vozTrip.Models.Answer", b =>
                {
                    b.Property<string>("AnswerId")
                        .HasColumnType("text")
                        .HasColumnName("answer_id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<string>("AudioPublicId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("audio_public_id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_id");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.HasKey("AnswerId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PoiId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.GuestSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("LanguageId")
                        .HasColumnType("text")
                        .HasColumnName("language_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("SessionId");

                    b.HasIndex("LanguageId");

                    b.ToTable("guest_sessions", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Language", b =>
                {
                    b.Property<string>("LanguageId")
                        .HasColumnType("text")
                        .HasColumnName("language_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language_name");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageCode")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Poi", b =>
                {
                    b.Property<string>("PoiId")
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PoiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("poi_name");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seller_id");

                    b.Property<double>("TriggerRadius")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(10.0)
                        .HasColumnName("trigger_radius");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("PoiId");

                    b.HasIndex("SellerId");

                    b.HasIndex("ZoneId");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.PoiLocalization", b =>
                {
                    b.Property<string>("LocalizationId")
                        .HasColumnType("text")
                        .HasColumnName("localization_id");

                    b.Property<int?>("AudioDuration")
                        .HasColumnType("integer")
                        .HasColumnName("audio_duration");

                    b.Property<string>("AudioPublicId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("audio_public_id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAutoTranslated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_auto_translated");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_id");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("LocalizationId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PoiId", "LanguageId")
                        .IsUnique();

                    b.ToTable("poi_localizations", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.PoiMedia", b =>
                {
                    b.Property<string>("MediaId")
                        .HasColumnType("text")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("media_url");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("public_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("MediaId");

                    b.HasIndex("PoiId");

                    b.ToTable("poi_media", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_id");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question_text");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("QuestionId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PoiId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Seller", b =>
                {
                    b.Property<string>("SellerId")
                        .HasColumnType("text")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ShopLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("shop_logo");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shop_name");

                    b.HasKey("SellerId");

                    b.HasIndex("ApprovedBy");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.VisitLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasColumnType("text")
                        .HasColumnName("log_id");

                    b.Property<string>("PoiId")
                        .HasColumnType("text")
                        .HasColumnName("poi_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("LogId");

                    b.HasIndex("PoiId");

                    b.HasIndex("SessionId");

                    b.ToTable("visit_logs", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Zone", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_name");

                    b.HasKey("ZoneId");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Answer", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Language", "Language")
                        .WithMany("Answers")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_vozTrip.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_vozTrip.Models.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("back_end_vozTrip.Models.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Poi");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.GuestSession", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Language", "Language")
                        .WithMany("GuestSessions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Language");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Poi", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Seller", "Seller")
                        .WithMany("Pois")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_vozTrip.Models.Zone", "Zone")
                        .WithMany("Pois")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Seller");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.PoiLocalization", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Language", "Language")
                        .WithMany("PoiLocalizations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_vozTrip.Models.Poi", "Poi")
                        .WithMany("Localizations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.PoiMedia", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Poi", "Poi")
                        .WithMany("Media")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Question", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Language", "Language")
                        .WithMany("Questions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end_vozTrip.Models.Poi", "Poi")
                        .WithMany("Questions")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Seller", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_end_vozTrip.Models.User", "User")
                        .WithOne("Seller")
                        .HasForeignKey("back_end_vozTrip.Models.Seller", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.VisitLog", b =>
                {
                    b.HasOne("back_end_vozTrip.Models.Poi", "Poi")
                        .WithMany("VisitLogs")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_end_vozTrip.Models.GuestSession", "GuestSession")
                        .WithMany("VisitLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuestSession");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.GuestSession", b =>
                {
                    b.Navigation("VisitLogs");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Language", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("GuestSessions");

                    b.Navigation("PoiLocalizations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Poi", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("Media");

                    b.Navigation("Questions");

                    b.Navigation("VisitLogs");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Seller", b =>
                {
                    b.Navigation("Pois");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.User", b =>
                {
                    b.Navigation("Seller");
                });

            modelBuilder.Entity("back_end_vozTrip.Models.Zone", b =>
                {
                    b.Navigation("Pois");
                });
#pragma warning restore 612, 618
        }
    }
}
